---
authority:
  default_aia: 
    issuer_url: http://localhost:7880/v1/certs/${ISSUER_ID}.crt
    crl_url: http://localhost:7880/v1/crl/${ISSUER_ID}.crl
    ocsp_url: http://localhost:7880/v1/ocsp
    # value in 72h format for duration of CRL next update time
    crl_expiry: 12h
    # value in 8h format for duration of CRL renewal before next update time
    crl_renewal: 1h
    # value in 8h format for duration of OCSP next update time
    ocsp_expiry: 30m

  issuers:
  -
    # specifies Issuer's label
    label: TrustyCA
    # specifies type: tls|codesign|timestamp|ocsp|spiffe|trusty
    type: trusty
    cert: /var/trusty/certs/trusty_issuer2_ca.pem
    key: /var/trusty/certs/trusty_issuer2_ca-key.pem
    # location of the CA bundle file
    ca_bundle: /var/trusty/certs/trusty_cabundle.pem
    # location of the Root CA file
    root_bundle: /var/trusty/roots/trusty_root_ca.pem

profiles:

  default:
    expiry: 168h
    backdate: 30m
    usages:
    - signing
    - key encipherment

  server:
    description: server profile
    issuer_label: TrustyCA
    expiry: 168h
    backdate: 30m
    usages:
    - signing
    - key encipherment
    - server auth
    - ipsec end system
    allowed_extensions:
    - 1.3.6.1.5.5.7.1.1

  client:
    description: client profile
    issuer_label: TrustyCA
    expiry: 168h
    backdate: 30m
    usages:
    - signing
    - key encipherment
    - client auth
    - ipsec user
    allowed_extensions:
    - 1.3.6.1.5.5.7.1.1

  peer:
    issuer_label: TrustyCA
    expiry: 168h
    backdate: 30m
    usages:
    - signing
    - key encipherment
    - server auth
    - client auth
    - ipsec user
    - ipsec end system
    allowed_extensions:
    - 1.3.6.1.5.5.7.1.1

  server:
    issuer_label: TrustyCA
    expiry: 168h
    backdate: 30m
    usages:
    - signing
    - key encipherment
    - server auth
    - ipsec end system
    allowed_extensions:
    - 1.3.6.1.5.5.7.1.1

  client:
    issuer_label: TrustyCA
    expiry: 168h
    backdate: 30m
    usages:
    - signing
    - key encipherment
    - client auth
    - ipsec user
    allowed_extensions:
    - 1.3.6.1.5.5.7.1.1

  ocsp:
    issuer_label: TrustyCA
    description: OCSP responder profile
    expiry: 8760h
    backdate: 30m
    usages:
    - digital signature
    - ocsp signing
    allowed_extensions:
    - 1.3.6.1.5.5.7.1.1

  timestamp:
    issuer_label: TrustyCA
    description: Timestamp certificate profile
    expiry: 43070h
    backdate: 30m
    usages:
    - digital signature
    - timestamping
    allowed_extensions:
    - 2.5.29.37

  codesign:
    issuer_label: TrustyCA
    description: Codesigning certificate profile
    expiry: 8760h
    backdate: 30m
    usages:
    - digital signature
    - code signing
    - key encipherment
