---
# specifies the Region / Datacenter where the instance is running
region: local
# specifies the environment where the instance is running: prod|stage|dev
environment: prod
# specifies the service name (to be used in logs, metrics, etc)
service: trusty
# specifies the cluster name
cluster: local

# configuration for the logger
logs:
  # contains where to store the log files; if value is empty, them stderr is used for output
  directory: /var/trusty/logs
  # controls how old files are before deletion / rotation
  max_age_days: 3
  # contols how large a single log file can be before its rotated
  max_size_mb: 10

log_levels: 
  - repo: "*"
    level: TRACE
  - repo: github.com/ekspand/trusty
    package: "*"
    level: TRACE
  - repo: github.com/ekspand/trusty/health
    package: xhttp
    level: ERROR
  - repo: github.com/ekspand/trusty/backend/service
    package: "*"
    level: DEBUG
  - repo: github.com/go-phorce/dolly
    package: "*"
    level: TRACE

# configuration for the audit logger
audit:
  directory: /var/trusty/audit
  max_age_days: 14
  max_size_mb: 10

metrics:
  # specifies if the metrics provider is disabled
  disabled: true
  # the metrics provider: prometeus|inmem
  provider: inmem

# configuration for crypto providers
crypto_provider:
  #  the location of the configuration file for default provider
  default: /var/trusty/softhsm/unittest_hsm.json
  # the list of locations of the configuration files
  providers:
  # the list of supported manufactures of PKCS11 tokens
  pkcs11_manufacturers:
    - SoftHSM
    - Gemalto NV

sql:
  # the driver name: postgres|mysql
  driver: postgres
  # specifies the connection string. It can be prefixed with file:// or env:// to load the source from a file or environment variable.
  data_source: env://TRUSTY_SQL_CONN
  # the directory that contains migrations.
  migrations_dir: /opt/trusty/bin/sql/postgres/migrations
        
# configuration for the authorization module
authz:
  # allow any non-authenticated request access to this path and its children
  allow_any:
    - /v1/auth
    - /v1/status
    - /v1/certs
    - /v1/crl
    - /v1/ocsp
    - /v1/roots
    - /trustypb.CertInfoService
    - /trustypb.StatusService
  # allow any authenticated request that includes a non empty role
  allow_any_role:
    - /v1/wf
    - /trustypb.AuthorityService/Issuers
    - /trustypb.AuthorityService/Roots
  # allow the specified roles access to this path and its children, in format: ${path}:${role},${role}
  allow:
    - /v1/ca:trusty-peer
    - /trustypb.AuthorityService:trusty-peer
  # specifies to log allowed access to Any role
  log_allowed_any: true
  # specifies to log allowed access
  log_allowed: true
  # specifies to log denied access
  log_denied: true

# configuration for the Identity mappers
identity:
  # location of the config file for certificate based identity
  cert_mapper: cert-roles.yaml
  # location of the config file for JWT based identity
  jwt_mapper: jwt-roles.yaml
  # location of the config file for API-Key based identity
  api_key_mapper:

# the configuration files for OAuth clients    
oauth_clients:
  - oauth-github.yaml

authority: ca-config.yaml
 
ra:
  # the list of private Root Certs files.
  private_roots:
    - /var/trusty/roots/trusty_root_ca.pem
  # the list of public Root Certs files.
  public_roots:


servers:
  cis:
    description: Certificate Information Service allows unauthenticated calls to AIA, OCSP and Certificates end-points
    listen_urls:
      - http://0.0.0.0:8080
    client_url: http://localhost:8080
    services:
      - status
      - cis
    heartbeat_secs: 30
    timeout:
      request: 3s
    keep_alive:
      min_time: 60s
      interval: 30s
      timeout: 180s

  wfe:
    description: Web Front End
    listen_urls:
      - https://0.0.0.0:7891
    client_url: https://localhost:7891
    server_tls:
      cert: /var/trusty/certs/trusty_peer.pem
      key: /var/trusty/certs/trusty_peer-key.pem
      trusted_ca: /var/trusty/roots/trusty_root_ca.pem
    services:
      - auth
      - status
      - workflow
    heartbeat_secs: 30
    timeout:
      request: 3s
    keep_alive:
      min_time: 60s
      interval: 30s
      timeout: 180s
    cors:
      enabled: true
      max_age: 600
      allow_credentials: true
      allowed_origins:
        - "*"
      allowed_methods:
        - HEAD
        - OPTIONS
        - GET
        - POST
        - DELETE
      allowed_headers:
        - Accept
        - Content-Type
        - Content-Length
        - Accept-Encoding
        - Authorization
        - User-Agent
        - Referer
        - X-Device-ID
        - sec-ch-ua
        - sec-ch-ua-mobile

  ca:
    description: Certification Authority
    listen_urls:
      - https://0.0.0.0:7892
    client_url: https://localhost:7892
    server_tls:
      cert: /var/trusty/certs/trusty_peer.pem
      key: /var/trusty/certs/trusty_peer-key.pem
      trusted_ca: /var/trusty/roots/trusty_root_ca.pem
    services:
      - status
      - ca
    heartbeat_secs: 30
    timeout:
      request: 3s
    keep_alive:
      min_time: 60s
      interval: 30s
      timeout: 180s

trusty_client: 
  client_tls:
    cert: /var/trusty/certs/trusty_peer.pem
    key: /var/trusty/certs/trusty_peer-key.pem
    trusted_ca: /var/trusty/roots/trusty_root_ca.pem
  server_url:
    cis: http://127.0.0.1:8080
    wfe: https://127.0.0.1:7891
    ca: https://127.0.0.1:7892
    ra: https://127.0.0.1:7893
