language: go
sudo: required
group: travis_latest
dist: xenial

language: go

go:
  - 1.15.x

env:
  - GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

addons:
  apt:
    packages:
      - softhsm2
      - opensc

install:
  - make vars tools folders

# Don't email me the results of the test runs.
notifications:
  email:
    on_success: change
    on_failure: always

before_script:
  - make vars generate

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - make vars hsmconfig build gen_test_certs start-sql covtest coveralls
