# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/base-debian10:nonroot

# RUN mkdir -p /app
COPY ./bin/kubecertinit /app/kubecertinit
WORKDIR /app

USER nonroot:nonroot

ENTRYPOINT ["/app/kubecertinit"]
