# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/base-debian10:nonroot
WORKDIR /
COPY ./bin/kubeca .
USER nonroot:nonroot

ENTRYPOINT ["/kubeca"]
