---
metrics:
  disabled: true
  prometheus:
    addr:

logs:
  directory: /dev/null

servers:
  cis:
    disabled: false
  ca:
    disabled: false

ra:
  publisher:
    # use gs:// for GCP, or file path
    cert_bucket: /tmp/trusty/dev-certs
    crl_bucket: /tmp/trusty/dev-crls

tasks: []

# configuration for crypto providers
crypto_provider:
  #  the location of the configuration file for default provider
  default: ${TRUSTY_CONFIG_DIR}/kms/aws-dev-kms.yaml
  # the list of locations of the configuration files
  providers:
  #  - /tmp/trusty/softhsm/unittest_hsm.json
  # the list of supported manufactures of PKCS11 tokens
  pkcs11_manufacturers:
    - SoftHSM
    - Gemalto NV
