---
# specifies the Region / Datacenter where the instance is running
region: dev
# specifies the environment where the instance is running: prod|stage|dev
environment: dev
# specifies the service name (to be used in logs, metrics, etc)
service: trusty
# specifies the cluster name
cluster: local

log_levels:
  - repo: "*"
    level: TRACE
  - repo: github.com/effective-security/trusty
    package: "*"
    level: TRACE
  - repo: github.com/effective-security/trusty/pkg
    package: "*"
    level: DEBUG
  - repo: github.com/effective-security/trusty/backend
    package: "*"
    level: DEBUG
  - repo: github.com/effective-security/trusty/health
    package: xhttp
    level: ERROR
  - repo: github.com/effective-security/trusty/backend/service
    package: "*"
    level: DEBUG
  - repo: github.com/effective-security/xpki
    package: authority
    level: DEBUG

metrics:
  # specifies if the metrics provider is disabled
  disabled: false
  prefix: trusty
  runtime_metrics: true
  allowed_prefixes:
  - trusty
  blocked_prefixes:
  - promhttp
  # the metrics provider: prometheus|inmem
  provider: prometheus
  prometheus:
    expiration: 1m
    addr: "127.0.0.1:19090"

# configuration for crypto providers
crypto_provider:
  #  the location of the configuration file for default provider
  default: ${TRUSTY_CONFIG_DIR}/kms/aws-dev-kms.yaml
  # the list of locations of the configuration files
  providers:
    - ${TRUSTY_CONFIG_DIR}/kms/aws-dev-kms-shaken.yaml
  # the list of supported manufactures of PKCS11 tokens
  pkcs11_manufacturers:
    - SoftHSM
    - Gemalto NV

jwt_provider: ${TRUSTY_CONFIG_DIR}/jwt-provider.yaml

ca_sql:
  # specifies the connection string. It can be prefixed with file:// or env:// to load the source from a file or environment variable.
  data_source: file://${TRUSTY_CONFIG_DIR}/sql-conn-cadb.txt
  # the directory that contains migrations.
  migrations_dir: ${TRUSTY_CONFIG_DIR}/../../sql/cadb/migrations
  # force_version: 1
  # migrate_version: 2

authority: ${TRUSTY_CONFIG_DIR}/ca-config.dev.yaml

delegated_issuers:
  crypto_provider: AWSKMS
  crypto_model: shaken
  issuer_label_prefix: DELEGATED_ICA_
  aia:
    #crl_url: https://authenticate-api.iconectiv.com/download/v1/crl
  allowed_profiles:
    - DELEGATED

tasks:
  - name: certsmonitor
    schedule: "every 10 minutes"
    args:
      - issuer:/tmp/trusty/certs/shaken_ca.pem
      - issuer:/tmp/trusty/certs/shaken_delegated_l1_ca.pem
      - peer:/tmp/trusty/certs/trusty_peer_ca.pem
      - client:/tmp/trusty/certs/trusty_client.pem
  - name: stats
    schedule: "every 13 minutes"
  - name: health_check
    schedule: "every 30 seconds"
    args: ["-hsmkeys", "-ca"]
  - name: health_check
    schedule: "every 60 seconds"
    args: ["-ocsp", "/tmp/trusty/certs/trusty_client.pem"]

ra:
  # the list of private Root Certs files.
  private_roots:
    - ${TRUSTY_CONFIG_DIR}/roots/trusty_root_ca.pem
  # the list of public Root Certs files.
  public_roots:
    - /tmp/trusty/certs/shaken_root_ca.pem
  publisher:
    base_url: https://dev.trustyca.com
    # use gs:// for GCP, or file path
    cert_bucket: /tmp/trusty/dev-certs
    crl_bucket: /tmp/trusty/dev-crls
  gen_certs:
    schedule: every 3 minutes
    profiles:
      - profile: peer
        disabled: false
        cert_file: /tmp/trusty/certs/trusty_peer_ca.pem
        key_file: /tmp/trusty/certs/trusty_peer_ca.key
        renewal: 165h
        san:
          - env.HOSTNAME
          - localhost
        csr_profile: ${TRUSTY_CONFIG_DIR}/csr_profile/trusty_peer.yaml
      - profile: client
        disabled: false
        cert_file: /tmp/trusty/certs/trusty_client.pem
        key_file: /tmp/trusty/certs/trusty_client.key
        renewal: 62h
        san:
          - spiffe://trusty/client
        csr_profile: ${TRUSTY_CONFIG_DIR}/csr_profile/trusty_client.yaml
      - profile: client
        disabled: false
        cert_file: /tmp/trusty/certs/trusty_admin.pem
        key_file: /tmp/trusty/certs/trusty_admin.key
        renewal: 62h
        san:
          - spiffe://trusty/admin
        csr_profile: ${TRUSTY_CONFIG_DIR}/csr_profile/trusty_admin.yaml

servers:
  cis:
    description: Certificate Information Service allows unauthenticated calls to AIA, OCSP and Certificates end-points
    disabled: false
    listen_urls:
      - http://0.0.0.0:7880
    services:
      - status
      - cis
      #- swagger
    timeout:
      request: 3s
    cors: &cors
      enabled: true
      max_age: 600
      allow_credentials: true
      allowed_origins:
        - "*"
      allowed_methods:
        - HEAD
        - OPTIONS
        - GET
        - POST
        - DELETE
      allowed_headers:
        - Accept
        - Content-Type
        - Content-Length
        - Accept-Encoding
        - Accept-Language
        - Authorization
        - User-Agent
        - Referer
        - X-Device-ID
        - Location
        - Link
        - Replay-Nonce
        - sec-ch-ua
        - sec-ch-ua-mobile
        - sec-fetch-dest
        - sec-fetch-mode
    # configuration for the authorization module
    authz:
      # allow any non-authenticated request access to this path and its children
      # /v1/* is allowed
      allow_any:
        - /favicon.ico
        - /v1
        - /metrics
        - /healthz
        - /pb.CIS
        - /pb.Status
      # allow any authenticated request that includes a non empty role
      allow_any_role:
      # allow the specified roles access to this path and its children, in format: ${path}:${role},${role}
      allow:
      # specifies to log allowed access to Any role
      log_allowed_any: true
      # specifies to log allowed access
      log_allowed: true
      # specifies to log denied access
      log_denied: true
    # configuration for the Identity mappers
    identity_map:
      tls:
        enabled: false
      jwt:
        enabled: false

  ca:
    description: Certification Authority
    disabled: false
    listen_urls:
      - https://0.0.0.0:7892
    client_url: https://localhost:7892
    server_tls:
      cert: /tmp/trusty/certs/trusty_peer_ca.pem
      key: /tmp/trusty/certs/trusty_peer_ca.key
      trusted_ca: ${TRUSTY_CONFIG_DIR}/roots/trusty_root_ca.pem
      client_cert_auth: false
    services:
      - status
      - ca
      - cis
    logger_skip_paths:
      - path: /v1/status/node
        agent: Google
      - path: /metrics
        agent: Prom
      - path: /pb.CA/ListIssuers
        agent: trusty-healthcheck
    timeout:
      request: 3s
    keep_alive:
      min_time: 60s
      interval: 30s
      timeout: 180s
    cors: *cors
    authz:
      # allow any non-authenticated request access to this path and its children
      # /v1/* is allowed
      allow_any:
        # allow any authenticated request that includes a non empty role
        - /pb.Status
        - /metrics
        - /healthz
        - /v1/status
        - /pb.Status
      allow_any_role:
        - /pb.CIS
        - /pb.CA
      # allow the specified roles access to this path and its children, in format: ${path}:${role},${role}
      allow:
        - /pb.CA/SignCertificate:trusty-wfe,trusty-ca,trusty-admin,trusty-ra
        - /pb.CA/SignOCSP:trusty-wfe,trusty-ca,trusty-admin,trusty-ra
        - /pb.CA/PublishCrls:trusty-ca,trusty-admin,trusty-ra
        - /pb.CA/RevokeCertificate:trusty-ca,trusty-admin,trusty-ra
        - /pb.CA/RegisterDelegatedIssuer:trusty-ca,trusty-admin,trusty-ra
        - /pb.CA/ArchiveDelegatedIssuer:trusty-ca,trusty-admin,trusty-ra
        - /pb.CA/UpdateCertificateLabel:trusty-ca,trusty-admin,trusty-ra
        - /pb.CA/RegisterProfile:trusty-ca,trusty-admin,trusty-ra
      # specifies to log allowed access to Any role
      log_allowed_any: true
      # specifies to log allowed access
      log_allowed: true
      # specifies to log denied access
      log_denied: true
    # configuration for the Identity mappers
    identity_map:
      tls:
        enabled: true
        default_authenticated_role: authenticated_tls
        roles:
          trusty-cis:
            - spiffe://trusty/cis
          trusty-ca:
            - spiffe://trusty/ca
          trusty-ra:
            - spiffe://trusty/ra
          trusty-wfe:
            - spiffe://trusty/wfe
          trusty-client:
            - spiffe://trusty/client
          trusty-admin:
            - spiffe://trusty/admin
      jwt:
        enabled: true
        audience: trusty
        default_authenticated_role: authenticated_jwt
        subject_claim: email
        roles:
          trusty-admin:
            - denis@ekspand.com
            - denis@effectivesecurity.pt

client:
  client_tls:
    cert: /tmp/trusty/certs/trusty_client.pem
    key: /tmp/trusty/certs/trusty_client.key
    trusted_ca: ${TRUSTY_CONFIG_DIR}/roots/trusty_root_ca.pem
  server_url:
    cis: http://localhost:7880
    ca: https://localhost:7892
  dial_timeout: 30s
  dial_keep_alive_time: 300s
  dial_keep_alive_timeout: 30s
