---
# specifies the Region / Datacenter where the instance is running
region: dev
# specifies the environment where the instance is running: prod|stage|dev
environment: test
# specifies the service name (to be used in logs, metrics, etc)
service: trusty
# specifies the cluster name
cluster: local

# configuration for the logger
logs:
  # contains where to store the log files; if value is empty, them stderr is used for output
  directory:
  # controls how old files are before deletion / rotation
  max_age_days: 3
  # contols how large a single log file can be before its rotated
  max_size_mb: 10

log_levels: 
  - repo: "*"
    level: TRACE
  - repo: github.com/ekspand/trusty
    package: "*"
    level: TRACE
  - repo: github.com/ekspand/trusty/pkg
    package: "*"
    level: DEBUG
  - repo: github.com/ekspand/trusty/backend
    package: "*"
    level: DEBUG
  - repo: github.com/ekspand/trusty/health
    package: xhttp
    level: ERROR
  - repo: github.com/ekspand/trusty/backend/service
    package: "*"
    level: DEBUG
  - repo: github.com/go-phorce/dolly
    package: "*"
    level: TRACE

# configuration for the audit logger
audit:
  directory: /tmp/trusty/audit
  max_age_days: 14
  max_size_mb: 10

metrics:
  # specifies if the metrics provider is disabled
  disabled: false
  # the metrics provider: prometeus|inmem
  provider: prometheus

# configuration for crypto providers
crypto_provider:
  #  the location of the configuration file for default provider
  default: /tmp/trusty/softhsm/unittest_hsm.json
  # the list of locations of the configuration files
  providers:
  # the list of supported manufactures of PKCS11 tokens
  pkcs11_manufacturers:
    - SoftHSM
    - Gemalto NV

jwt_provider: ${TRUSTY_CONFIG_DIR}/jwt-provider.yaml

orgs_sql:
  # the driver name: postgres|mysql
  driver: postgres
  # specifies the connection string. It can be prefixed with file:// or env:// to load the source from a file or environment variable.
  data_source: file://${TRUSTY_CONFIG_DIR}/sql-conn-orgsdb.txt
  # the directory that contains migrations.
  migrations_dir: ${TRUSTY_CONFIG_DIR}/../../sql/orgsdb/migrations

ca_sql:
  # the driver name: postgres|mysql
  driver: postgres
  # specifies the connection string. It can be prefixed with file:// or env:// to load the source from a file or environment variable.
  data_source: file://${TRUSTY_CONFIG_DIR}/sql-conn-cadb.txt
  # the directory that contains migrations.
  migrations_dir: ${TRUSTY_CONFIG_DIR}/../../sql/cadb/migrations

# the configuration files for OAuth clients    
oauth_clients:
  - ${TRUSTY_CONFIG_DIR}/oauth-github.yaml
  - ${TRUSTY_CONFIG_DIR}/oauth-google.yaml

# the configuration files for email providers 
email_providers:
  - ${TRUSTY_CONFIG_DIR}/email-provider-mailgun.yaml

acme: ${TRUSTY_CONFIG_DIR}/acme.yaml

authority: ${TRUSTY_CONFIG_DIR}/ca-config.dev.yaml

ra:
  # the list of private Root Certs files.
  private_roots:
    - ${TRUSTY_CONFIG_DIR}/roots/trusty_dev_root_ca.pem
    - ${TRUSTY_CONFIG_DIR}/roots/trusty_root_ca.pem
  # the list of public Root Certs files.
  public_roots:
    - ${TRUSTY_CONFIG_DIR}/roots/martini_root_ca.pem
    - ${TRUSTY_CONFIG_DIR}/roots/martini_dev_root_ca.pem

servers:
  cis:
    description: Certificate Information Service allows unauthenticated calls to AIA, OCSP and Certificates end-points
    disabled: false
    listen_urls:
      - http://0.0.0.0:7880
    client_url: http://localhost:7880
    services:
      - status
      - cis
      - swagger
    enable_grpc_gateway: false
    heartbeat_secs: 30
    timeout:
      request: 3s
    swagger:
      enabled: true
      files:
        cis: "${TRUSTY_CONFIG_DIR}/../../Documentation/dev-guide/apispec/swagger/cis.swagger.json"
        status: "${TRUSTY_CONFIG_DIR}/../../Documentation/dev-guide/apispec/swagger/status.swagger.json"
    cors: &cors
      enabled: true
      max_age: 600
      allow_credentials: true
      allowed_origins:
        - "*"
      allowed_methods:
        - HEAD
        - OPTIONS
        - GET
        - POST
        - DELETE
      allowed_headers:
        - Accept
        - Content-Type
        - Content-Length
        - Accept-Encoding
        - Accept-Language
        - Authorization
        - User-Agent
        - Referer
        - X-Device-ID
        - sec-ch-ua
        - sec-ch-ua-mobile
        - sec-fetch-dest
        - sec-fetch-mode
    # configuration for the authorization module
    authz:
      # allow any non-authenticated request access to this path and its children
      # /v1/* is allowed
      allow_any:
        - /favicon.ico
        - /v1
        - /pb.CIService
        - /pb.StatusService
      # allow any authenticated request that includes a non empty role
      allow_any_role:
      # allow the specified roles access to this path and its children, in format: ${path}:${role},${role}
      allow:
      # specifies to log allowed access to Any role
      log_allowed_any: false
      # specifies to log allowed access
      log_allowed: true
      # specifies to log denied access
      log_denied: true
    # configuration for the Identity mappers
    identity_map:
      tls:
        enabled:  false
      jwt:
        enabled:  false

  wfe:
    description: Web Front End
    disabled: false
    listen_urls:
      - https://0.0.0.0:7891
    client_url: https://localhost:7891
    server_tls:
      cert: /tmp/trusty/certs/trusty_dev_peer_wfe.pem
      key: /tmp/trusty/certs/trusty_dev_peer_wfe-key.pem
      trusted_ca: ${TRUSTY_CONFIG_DIR}/roots/trusty_dev_root_ca.pem
      # client_cert_auth: true
    services:
      - acme
      - auth
      - status
      - workflow
      - martini
    enable_grpc_gateway: false
    heartbeat_secs: 30
    timeout:
      request: 3s
    keep_alive:
      min_time: 60s
      interval: 30s
      timeout: 180s
    cors: *cors
    authz:
      # allow any non-authenticated request access to this path and its children
      # /v1/* is allowed
      allow_any:
        - /
        - /favicon.ico
        - /v1
        - /v1/auth
        - /v1/ms/approve_org
        - /v2/acme
        - /pb.StatusService
      # allow any authenticated request that includes a non empty role
      allow_any_role:
        - /v1/wf
        - /v1/ms
        - /v1/auth/token
      # allow the specified roles access to this path and its children, in format: ${path}:${role},${role}
      allow:
      # specifies to log allowed access to Any role
      log_allowed_any: false
      # specifies to log allowed access
      log_allowed: true
      # specifies to log denied access
      log_denied: true
    # configuration for the Identity mappers
    identity_map:
      tls:
        enabled:  true
        default_authenticated_role: authenticated_tls
        roles:
          trusty:
            - spifee://trusty/all
          trusty-cis:
            - spifee://trusty/cis
          trusty-ca:
            - spifee://trusty/ca
          trusty-ra:
            - spifee://trusty/ra
          trusty-wfe:
            - spifee://trusty/wfe
      jwt:
        enabled:  true
        audience: trusty
        default_authenticated_role: authenticated_jwt
        roles:
          trusty-admin:
          - denis@ekspand.com

  ca:
    description: Certification Authority
    disabled: false
    listen_urls:
      - https://0.0.0.0:7892
    client_url: https://localhost:7892
    server_tls:
      cert: /tmp/trusty/certs/trusty_dev_peer_ca.pem
      key: /tmp/trusty/certs/trusty_dev_peer_ca-key.pem
      trusted_ca: ${TRUSTY_CONFIG_DIR}/roots/trusty_dev_root_ca.pem
      client_cert_auth: true
    services:
      - status
      - ca
      - swagger
    enable_grpc_gateway: false
    heartbeat_secs: 30
    timeout:
      request: 3s
    keep_alive:
      min_time: 60s
      interval: 30s
      timeout: 180s
    swagger:
      enabled: true
      files:
        ca: "${TRUSTY_CONFIG_DIR}/../../Documentation/dev-guide/apispec/swagger/ca.swagger.json"
        status: "${TRUSTY_CONFIG_DIR}/../../Documentation/dev-guide/apispec/swagger/status.swagger.json"
    cors: *cors
    authz:
      # allow any non-authenticated request access to this path and its children
      # /v1/* is allowed
      allow_any:
      # allow any authenticated request that includes a non empty role
        - /pb.StatusService
      allow_any_role:
        - /pb.CAService/ProfileInfo
        - /pb.CAService/Issuers
        - /pb.CIService
      # allow the specified roles access to this path and its children, in format: ${path}:${role},${role}
      allow:
        - /pb.CAService/SignCertificate:trusty-wfe,trusty-ra,trusty-admin,trusty
        - /pb.CAService/PublishCrls:trusty-ra,trusty-admin,trusty
        - /pb.CAService/RevokeCertificate:trusty-ra,trusty-admin,trusty
      # specifies to log allowed access to Any role
      log_allowed_any: false
      # specifies to log allowed access
      log_allowed: true
      # specifies to log denied access
      log_denied: true
    # configuration for the Identity mappers
    identity_map:
      tls:
        enabled:  true
        default_authenticated_role: authenticated_tls
        roles:
          trusty:
            - spifee://trusty/all
          trusty-cis:
            - spifee://trusty/cis
          trusty-ca:
            - spifee://trusty/ca
          trusty-ra:
            - spifee://trusty/ra
          trusty-wfe:
            - spifee://trusty/wfe
      jwt:
        enabled: true
        audience: trusty
        default_authenticated_role: authenticated_jwt
        roles:
          trusty-admin:
          - denis@ekspand.com

  ra:
    description: Registration Authority
    disabled: false
    listen_urls:
      - https://0.0.0.0:7893
    client_url: https://localhost:7893
    server_tls:
      cert: /tmp/trusty/certs/trusty_dev_peer_ra.pem
      key: /tmp/trusty/certs/trusty_dev_peer_ra-key.pem
      trusted_ca: ${TRUSTY_CONFIG_DIR}/roots/trusty_dev_root_ca.pem
      client_cert_auth: true
    services:
      - status
      - ra
      - swagger
    enable_grpc_gateway: false
    heartbeat_secs: 30
    timeout:
      request: 3s
    keep_alive:
      min_time: 60s
      interval: 30s
      timeout: 180s
    swagger:
      enabled: true
      files:
        ra: "${TRUSTY_CONFIG_DIR}/../../Documentation/dev-guide/apispec/swagger/ra.swagger.json"
        status: "${TRUSTY_CONFIG_DIR}/../../Documentation/dev-guide/apispec/swagger/status.swagger.json"
    cors: *cors
    authz:
      # allow any non-authenticated request access to this path and its children
      # /v1/* is allowed
      allow_any:
      # allow any authenticated request that includes a non empty role
        - /pb.StatusService
      allow_any_role:
        - /pb.RAService/GetRoots
      # allow the specified roles access to this path and its children, in format: ${path}:${role},${role}
      allow:
        - /pb.RAService:trusty-wfe,trusty-admin,trusty
      # specifies to log allowed access to Any role
      log_allowed_any: false
      # specifies to log allowed access
      log_allowed: true
      # specifies to log denied access
      log_denied: true
    # configuration for the Identity mappers
    identity_map:
      tls:
        enabled:  true
        default_authenticated_role: authenticated_tls
        roles:
          trusty:
            - spifee://trusty/all
          trusty-cis:
            - spifee://trusty/cis
          trusty-ca:
            - spifee://trusty/ca
          trusty-ra:
            - spifee://trusty/ra
          trusty-wfe:
            - spifee://trusty/wfe
      jwt:
        enabled: true
        audience: trusty
        default_authenticated_role: authenticated_jwt
        roles:
          trusty-admin:
          - denis@ekspand.com

trusty_client: 
  client_tls:
    cert: /tmp/trusty/certs/trusty_dev_client.pem
    key: /tmp/trusty/certs/trusty_dev_client-key.pem
    trusted_ca: ${TRUSTY_CONFIG_DIR}/roots/trusty_dev_root_ca.pem
  server_url:
    cis: ["http://localhost:7880"]
    wfe: ["https://localhost:7891"]
    ca: ["https://localhost:7892"]
    ra: ["https://localhost:7893"]
  dial_timeout: 30s
  dial_keep_alive_time: 6s
  dial_keep_alive_timeout: 30s
