---
metrics:
  disabled: true
logs:
  directory: /dev/null
audit:
  directory: /dev/null

servers:
  cis:
    disabled: false
  ca:
    disabled: false

ra:
  publisher:
    # use gs:// for GCP, or file path 
    cert_bucket: /tmp/trusty/martini-dev-certs
    crl_bucket: /tmp/trusty/martini-dev-crls

tasks: []
