---
metrics:
  disabled: true
logs:
  directory: /dev/null
audit:
  directory: /dev/null

martini:
  poll_payment_status_interval: 1s
  poll_payment_status_timeout: 3s
  fcc_timeout: 5s

servers:
  cis:
    disabled: false
  wfe:
    disabled: false
  ca:
    disabled: false
  ra:
    disabled: false

ra:
  publisher:
    # use gs:// for GCP, or file path 
    cert_bucket: /tmp/trusty/martini-dev-certs
    crl_bucket: /tmp/trusty/martini-dev-crls

tasks: []
