---
metrics:
  disabled: true
logs:
  directory: /dev/null
audit:
  directory: /dev/null

servers:
  cis:
    disabled: false
  wfe:
    disabled: false
  ca:
    disabled: false
  ra:
    disabled: false