// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.6.1
// source: cis.proto

package pb

import (
	context "context"
	reflect "reflect"
	sync "sync"

	_ "github.com/gogo/googleapis/google/api"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RootsResponse provides response for GetRootsRequest
type RootsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roots []*RootCertificate `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
}

func (x *RootsResponse) Reset() {
	*x = RootsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootsResponse) ProtoMessage() {}

func (x *RootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootsResponse.ProtoReflect.Descriptor instead.
func (*RootsResponse) Descriptor() ([]byte, []int) {
	return file_cis_proto_rawDescGZIP(), []int{0}
}

func (x *RootsResponse) GetRoots() []*RootCertificate {
	if x != nil {
		return x.Roots
	}
	return nil
}

var File_cis_proto protoreflect.FileDescriptor

var file_cis_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x0a, 0x70, 0x6b, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6f, 0x74,
	0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x6f,
	0x74, 0x73, 0x32, 0x5c, 0x0a, 0x0f, 0x43, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x05, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6f, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x69, 0x73, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x73,
	0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x6b, 0x73, 0x70, 0x61, 0x6e, 0x64, 0x2f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cis_proto_rawDescOnce sync.Once
	file_cis_proto_rawDescData = file_cis_proto_rawDesc
)

func file_cis_proto_rawDescGZIP() []byte {
	file_cis_proto_rawDescOnce.Do(func() {
		file_cis_proto_rawDescData = protoimpl.X.CompressGZIP(file_cis_proto_rawDescData)
	})
	return file_cis_proto_rawDescData
}

var file_cis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cis_proto_goTypes = []interface{}{
	(*RootsResponse)(nil),   // 0: pb.RootsResponse
	(*RootCertificate)(nil), // 1: pb.RootCertificate
	(*empty.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_cis_proto_depIdxs = []int32{
	1, // 0: pb.RootsResponse.roots:type_name -> pb.RootCertificate
	2, // 1: pb.CertInfoService.Roots:input_type -> google.protobuf.Empty
	0, // 2: pb.CertInfoService.Roots:output_type -> pb.RootsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cis_proto_init() }
func file_cis_proto_init() {
	if File_cis_proto != nil {
		return
	}
	file_pkix_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cis_proto_goTypes,
		DependencyIndexes: file_cis_proto_depIdxs,
		MessageInfos:      file_cis_proto_msgTypes,
	}.Build()
	File_cis_proto = out.File
	file_cis_proto_rawDesc = nil
	file_cis_proto_goTypes = nil
	file_cis_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CertInfoServiceClient is the client API for CertInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CertInfoServiceClient interface {
	// Roots returns the root CAs
	Roots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RootsResponse, error)
}

type certInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertInfoServiceClient(cc grpc.ClientConnInterface) CertInfoServiceClient {
	return &certInfoServiceClient{cc}
}

func (c *certInfoServiceClient) Roots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RootsResponse, error) {
	out := new(RootsResponse)
	err := c.cc.Invoke(ctx, "/pb.CertInfoService/Roots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertInfoServiceServer is the server API for CertInfoService service.
type CertInfoServiceServer interface {
	// Roots returns the root CAs
	Roots(context.Context, *empty.Empty) (*RootsResponse, error)
}

// UnimplementedCertInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCertInfoServiceServer struct {
}

func (*UnimplementedCertInfoServiceServer) Roots(context.Context, *empty.Empty) (*RootsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Roots not implemented")
}

func RegisterCertInfoServiceServer(s *grpc.Server, srv CertInfoServiceServer) {
	s.RegisterService(&_CertInfoService_serviceDesc, srv)
}

func _CertInfoService_Roots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertInfoServiceServer).Roots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CertInfoService/Roots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertInfoServiceServer).Roots(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CertInfoService",
	HandlerType: (*CertInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Roots",
			Handler:    _CertInfoService_Roots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cis.proto",
}
