version: "3"

networks:
  trusty_private:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.88.0/24

volumes:
  trusty-shared-certs:

services:
  trusty-sql:
    image: ekspand/docker-centos7-postgres:latest
    domainname: trusty-sql.ekspand.com
    networks:
      trusty_private:
        ipv4_address: 10.77.88.100
        aliases:
          - trusty-sql.ekspand.com
    volumes:
      # Mounts the volumes from build container to the container in test
      # docker-compose command runs with ./scripts/integration as CWD, 
      # the source path in the volume definitions are relative to ./scripts/integration
      - ../../sql/postgres:/scripts/pgsql
    ports:
      - "5432" # SQL
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    entrypoint:
      - /bin/bash
      - -c
      - /start_postgres.sh

  trusty-node1:
    image: ekspand/trusty:latest
    domainname: node1.trusty.ca
    networks:
      trusty_private:
        ipv4_address: 10.77.88.101
        aliases:
          - node1.trusty.ca
    volumes:
      - trusty-shared-certs:/var/trusty/roots
        # Mounts the volumes from build container to the container in test
        # docker-compose command runs with ./scripts/integration as CWD, 
        # the source path in the volume definitions are relative to ./scripts/integration
      - ./tests:/opt/trusty/tests
    ports:
      - "8080" # Public WebAPI
      - "7891"
    environment:
      - TRUSTY_GITHUB_CLIENT_SECRET=not_used_in_test
      - TRUSTY_SQL_CONN=host=10.77.88.100 port=5432 user=postgres password=postgres sslmode=disable dbname=trustydb
    entrypoint:
      - /bin/bash
      - -c
      - >-
        /opt/trusty/bin/sql/postgres/wait_sql.sh 10.77.88.100 5432 postgres postgres echo "SQL is ready" &&
        /opt/trusty/tests/if-root-exists.sh mkdir -p /tmp/trusty/softhsm/tokens /tmp/trusty/certs &&
        /opt/trusty/bin/config-softhsm.sh
        --tokens-dir /tmp/trusty/softhsm/tokens
        --pin-file /tmp/trusty/softhsm/trusty_unittest.txt
        --generate-pin -s trusty_unittest
        -o /tmp/trusty/softhsm/unittest_hsm.json
        --delete --list-slots --list-object &&
        /opt/trusty/bin/gen_test_certs.sh
        --hsm-config /tmp/trusty/softhsm/unittest_hsm.json
        --ca-config /opt/trusty/etc/prod/ca-config.bootstrap.json
        --out-dir /var/trusty/certs
        --csr-dir /opt/trusty/etc/prod/csr
        --root-ca /var/trusty/roots/trusty_root_ca.pem
        --root-ca-key /var/trusty/roots/trusty_root_ca-key.pem
        --prefix trusty_
        --san 10.77.88.101
        --ca1 --ca2 --bundle --peer --force &&
        /opt/trusty/bin/trusty --std
        --hsm-cfg=/tmp/trusty/softhsm/unittest_hsm.json
        --cfg=/opt/trusty/etc/prod/trusty-config.json
        --logs-dir=/var/trusty/logs
        --audit-dir=/var/trusty/audit
        --host-name=10.77.88.101
        --health-listen-url=http://10.77.88.101:8080
        --client-listen-url=https://10.77.88.101:7891
  test-runner:
    image: ekspand/trusty:latest
    domainname: tester.trusty.ca
    networks:
      trusty_private:
        ipv4_address: 10.77.88.106
        aliases:
          - tester.trusty.ca
    volumes:
      - trusty-shared-certs:/var/trusty/roots
      # Mounts the volumes from build container to the container in test
      # docker-compose command runs with ./scripts/integration as CWD, 
      # the source path in the volume definitions are relative to ./scripts/integration
      - ./tests:/opt/trusty/tests
    depends_on:
      - trusty-node1
    links:
      - trusty-node1
    entrypoint:
      - /bin/bash
      - -c
      - >-
        mkdir -p /tmp/trusty/softhsm/tokens /var/trusty/certs &&
        /opt/trusty/bin/sql/postgres/create_sql.sh 10.77.88.100 5432 postgres postgres
        /opt/trusty/bin/config-softhsm.sh
        --tokens-dir /tmp/trusty/softhsm/tokens
        --pin-file /tmp/trusty/softhsm/trusty_unittest.txt
        --generate-pin -s trusty_unittest
        -o /tmp/trusty/softhsm/unittest_hsm.json
        --delete --list-slots --list-object &&
        /opt/trusty/bin/gen_test_certs.sh
        --hsm-config inmem
        --ca-config /opt/trusty/etc/prod/ca-config.bootstrap.json
        --out-dir /var/trusty/certs
        --csr-dir /opt/trusty/etc/prod/csr
        --root-ca /var/trusty/roots/trusty_root_ca.pem
        --root-ca-key /var/trusty/roots/trusty_root_ca-key.pem
        --prefix trusty_
        --root --ca1 --ca2 --bundle --client --peer &&
        /opt/trusty/tests/if-trusty-ready.sh /opt/trusty/tests/run.sh
