name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  context-info:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT" && \
          echo "GITHUB_REF=$GITHUB_REF GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
      - name: Repo info
        run: |
          curl -s \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}

  TestAndDeploy:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      EVENT_NUMBER: ${{ github.event.number }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.BUILDER_PAT }}
        run: git config --global url."https://dissoupov:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare
        run: make vars tools folders generate  version change_log

      - name: UnitTest
        run: make build start-local-deps gen_test_certs gen_shaken_certs covtest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker trusty meta
        id: meta_trusty
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            effectivesecurity/trusty
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker trusty docker/build-push-action@v2
        id: docker_build_trusty
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta_trusty.outputs.tags }}
          labels: ${{ steps.meta_trusty.outputs.labels }}

      - name: Integration Test
        env:
          ITEST_IMAGE_TAG: ${{ fromJSON(steps.meta_trusty.outputs.json).labels['org.opencontainers.image.version'] }}
        run: |
          echo "ITEST_IMAGE_TAG=$ITEST_IMAGE_TAG"
          make docker-citest

      - name: coveralls
        # if: github.event_name == 'pull_request'
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coveralls-github
