name: Set Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name, or skip for default'
        required: false

env:
  RUN_ID: ${{ github.run_id }}
  # A unique number for each run of a particular workflow in a repository.
  # This number begins at 1 for the workflow's first run, and increments with each new run.
  # This number does not change if you re-run the workflow run.
  RUN_NUMBER: ${{ github.run_number }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: set-tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "No tag provided, using default"         
            VERSION=$(cat .VERSION).$(git rev-list --count HEAD)
            echo "VERSION: ${VERSION}"
            echo "DIST_VERSION=${VERSION}" >> $GITHUB_ENV
          else
            echo "DIST_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            const {DIST_VERSION} = process.env          
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${DIST_VERSION}`,
                sha: context.sha
            })
